import React from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { CheckCircleIcon, ExclamationCircleIcon } from "@heroicons/react/24/outline";

const items=[{t:"Semantic HTML",d:"We use proper HTML5 semantic elements for screen reader navigation."},{t:"Keyboard Navigation",d:"All interactive elements are operable via keyboard."},{t:"Focus Indicators",d:"Visible focus indicators on all interactive elements."},{t:"Color Contrast",d:"Sufficient contrast ratios for readability."},{t:"Alt Text",d:"All meaningful images include descriptive alt text."},{t:"Form Accessibility",d:"All form fields include labels and aria attributes."},{t:"Responsive Design",d:"Works across all device sizes."},{t:"Reduced Motion",d:"Respects prefers-reduced-motion media query."}];
const lims=["Uploaded PDFs may not meet accessibility standards.","AI responses may not always use accessible formatting.","Some third-party content may not be fully accessible."];
export default function AccessibilityStatementPage(){return(<div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.6}}>
<h1 className="text-4xl font-bold text-white mb-2"><span className="bg-gradient-to-r from-brand-400 to-accent-500 bg-clip-text text-transparent">Accessibility Statement</span></h1>
<p className="text-gray-400 mb-8">Last updated: September 2, 2026</p>
<div className="space-y-8">
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Our Commitment</h2><p className="text-gray-300 leading-relaxed">SmartPYQ is committed to making our educational platform accessible to all students, including those with disabilities. We believe every student deserves equal access to exam preparation materials and AI-powered study tools.</p></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-6">Accessibility Features</h2><div className="grid gap-4">{items.map((x,i)=><div key={i} className="flex items-start gap-4 p-4 bg-white/5 rounded-xl"><CheckCircleIcon className="h-6 w-6 text-green-400 flex-shrink-0 mt-0.5" /><div><h3 className="text-white font-semibold mb-1">{x.t}</h3><p className="text-gray-400 text-sm leading-relaxed">{x.d}</p></div></div>)}</div></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Known Limitations</h2><ul className="space-y-3">{lims.map((x,i)=><li key={i} className="flex items-start gap-3 text-gray-300"><ExclamationCircleIcon className="h-5 w-5 text-amber-400 flex-shrink-0 mt-0.5" /><span className="text-sm">{x}</span></li>)}</ul></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Assistive Technology</h2><p className="text-gray-300 leading-relaxed">SmartPYQ is designed to be compatible with major screen readers including NVDA, JAWS, VoiceOver, and TalkBack.</p></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Feedback</h2><p className="text-gray-300 leading-relaxed">Contact us at <span className="text-brand-400">smartpyq@gmail.com</span> or <Link to="/report-issue" className="text-brand-400 hover:text-brand-300 underline">Report an Issue</Link> for accessibility feedback.</p></section>
<div className="text-center"><Link to="/" className="text-brand-400 hover:text-brand-300 transition-colors">Return to Home</Link></div>
</div></motion.div></div></div>);}
