import React from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { CheckCircleIcon, XCircleIcon } from "@heroicons/react/24/outline";

const permitted=["Upload previous year question papers you have the right to share","Use AI assistance for study preparation","Search and download papers for personal study","Bookmark and organize questions","Share SmartPYQ resources with fellow students","Report content issues or suggest improvements"];
const prohibited=[{t:"Copyright Infringement",d:"Upload content you do not have the right to distribute"},{t:"Malicious Content",d:"Upload files containing malware or harmful code"},{t:"Academic Dishonesty",d:"Use the platform to facilitate cheating"},{t:"Harassment",d:"Use the platform to harass or bully others"},{t:"System Abuse",d:"Exploit or compromise platform security"},{t:"Spam",d:"Use automated tools to scrape or spam features"},{t:"Impersonation",d:"Create accounts under false identities"},{t:"Commercial Exploitation",d:"Use for unauthorized commercial purposes"}];
export default function AcceptableUsePage(){return(<div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.6}}>
<h1 className="text-4xl font-bold text-white mb-2"><span className="bg-gradient-to-r from-brand-400 to-accent-500 bg-clip-text text-transparent">Acceptable Use Policy</span></h1>
<p className="text-gray-400 mb-8">Last updated: September 2, 2026</p>
<div className="space-y-8">
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Purpose</h2><p className="text-gray-300 leading-relaxed">SmartPYQ is an educational platform for exam preparation. This policy outlines rules for responsible platform use.</p></section>
<section className="bg-green-500/5 backdrop-blur-sm border border-green-500/20 rounded-2xl p-8"><h2 className="text-2xl font-bold text-green-400 mb-6 flex items-center gap-3"><CheckCircleIcon className="h-7 w-7" /> Permitted Uses</h2><ul className="space-y-3">{permitted.map((x,i)=><li key={i} className="flex items-start gap-3 text-gray-300"><CheckCircleIcon className="h-5 w-5 text-green-400 flex-shrink-0 mt-0.5" /><span>{x}</span></li>)}</ul></section>
<section className="bg-red-500/5 backdrop-blur-sm border border-red-500/20 rounded-2xl p-8"><h2 className="text-2xl font-bold text-red-400 mb-6 flex items-center gap-3"><XCircleIcon className="h-7 w-7" /> Prohibited Uses</h2><div className="grid gap-4">{prohibited.map((x,i)=><div key={i} className="flex items-start gap-4 p-4 bg-white/5 rounded-xl"><XCircleIcon className="h-6 w-6 text-red-400 flex-shrink-0 mt-0.5" /><div><h3 className="text-white font-semibold mb-1">{x.t}</h3><p className="text-gray-400 text-sm">{x.d}</p></div></div>)}</div></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Upload Guidelines</h2><ul className="space-y-2 text-gray-300"><li>1. You have the right to share the document</li><li>2. The document is a genuine academic question paper</li><li>3. The document contains no harmful content</li><li>4. You provide accurate metadata (subject, year, semester)</li></ul></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Consequences</h2><p className="text-gray-300 leading-relaxed">Violations may result in warnings, content removal, temporary suspension, or permanent account termination.</p></section>
<section className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-4">Reporting</h2><p className="text-gray-300 leading-relaxed">Report violations through <Link to="/report-issue" className="text-brand-400 hover:text-brand-300 underline">Report Issue</Link> or contact <span className="text-brand-400">smartpyq@gmail.com</span>.</p></section>
<div className="text-center"><Link to="/" className="text-brand-400 hover:text-brand-300 transition-colors">Return to Home</Link></div>
</div></motion.div></div></div>);}
